// <auto-generated />
using System;
using LotoAnalytics.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LotoAnalytics.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(LotoAnalyticsDbContext))]
    [Migration("20260725132957_AddConcursoGanhadoresMunicipios")]
    partial class AddConcursoGanhadoresMunicipios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.Contest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Accumulated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acumulado");

                    b.Property<decimal?>("CollectedAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_arrecadado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DrawCityState")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("municipio_uf_sorteio");

                    b.Property<DateOnly?>("DrawDate")
                        .HasColumnType("date")
                        .HasColumnName("data_apuracao");

                    b.Property<string>("DrawLocation")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("local_sorteio");

                    b.Property<bool>("LatestContest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ultimo_concurso");

                    b.Property<long>("LotteryModeId")
                        .HasColumnType("bigint")
                        .HasColumnName("modalidade_id");

                    b.Property<decimal?>("NextContestAccumulatedValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_acumulado_proximo_concurso");

                    b.Property<DateOnly?>("NextContestDate")
                        .HasColumnType("date")
                        .HasColumnName("data_proximo_concurso");

                    b.Property<decimal?>("NextContestEstimatedValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_estimado_proximo_concurso");

                    b.Property<int?>("NextContestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_concurso_proximo");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int?>("PreviousContestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_concurso_anterior");

                    b.Property<string>("RawResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("SpecialResult")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("resultado_especial");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("LotteryModeId", "Number")
                        .IsUnique();

                    b.ToTable("concursos", (string)null);
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint")
                        .HasColumnName("concurso_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NumberType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer")
                        .HasColumnName("valor_numero");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContestId", "NumberType", "Position")
                        .IsUnique();

                    b.ToTable("concurso_dezenas", (string)null);
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestPrizeTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint")
                        .HasColumnName("concurso_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descricao_faixa");

                    b.Property<decimal>("PrizeValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_premio");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("faixa");

                    b.Property<int>("WinnersCount")
                        .HasColumnType("integer")
                        .HasColumnName("numero_ganhadores");

                    b.HasKey("Id");

                    b.HasIndex("ContestId", "Tier")
                        .IsUnique();

                    b.ToTable("concurso_rateios", (string)null);
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestWinnerCity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("municipio");

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint")
                        .HasColumnName("concurso_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<int>("WinnersCount")
                        .HasColumnType("integer")
                        .HasColumnName("ganhadores");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("concurso_ganhadores_municipios", (string)null);
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.LotteryMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<int?>("CaixaGameNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_jogo_caixa");

                    b.Property<string>("CaixaGameType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_jogo_caixa");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("HasHeartTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("possui_time_coracao");

                    b.Property<bool>("HasLuckyMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("possui_mes_sorte");

                    b.Property<bool>("HasTrevos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("possui_trevos");

                    b.Property<int>("MainNumbersCount")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_dezenas_principal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int?>("SecondDrawNumbersCount")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_dezenas_segundo_sorteio");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CaixaGameType")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("modalidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CaixaGameNumber = 25,
                            CaixaGameType = "LOTOFACIL",
                            Code = "lotofacil",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 15,
                            Name = "Lotofacil",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            CaixaGameNumber = 2,
                            CaixaGameType = "MEGA_SENA",
                            Code = "mega_sena",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 6,
                            Name = "Mega-Sena",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            CaixaGameNumber = 5,
                            CaixaGameType = "QUINA",
                            Code = "quina",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 5,
                            Name = "Quina",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            CaixaGameNumber = 33,
                            CaixaGameType = "MAIS_MILIONARIA",
                            Code = "maismilionaria",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = true,
                            MainNumbersCount = 6,
                            Name = "+Milionaria",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            CaixaGameNumber = 7,
                            CaixaGameType = "LOTOMANIA",
                            Code = "lotomania",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 20,
                            Name = "Lotomania",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            CaixaGameNumber = 10,
                            CaixaGameType = "TIMEMANIA",
                            Code = "timemania",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = true,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 7,
                            Name = "Timemania",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            CaixaGameNumber = 12,
                            CaixaGameType = "DUPLA_SENA",
                            Code = "dupla_sena",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 6,
                            Name = "Dupla Sena",
                            SecondDrawNumbersCount = 6,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            CaixaGameNumber = 31,
                            CaixaGameType = "DIA_DE_SORTE",
                            Code = "dia_de_sorte",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = true,
                            HasTrevos = false,
                            MainNumbersCount = 7,
                            Name = "Dia de Sorte",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            CaixaGameNumber = 32,
                            CaixaGameType = "SUPER_SETE",
                            Code = "super_sete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HasHeartTeam = false,
                            HasLuckyMonth = false,
                            HasTrevos = false,
                            MainNumbersCount = 7,
                            Name = "Super Sete",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.Contest", b =>
                {
                    b.HasOne("LotoAnalytics.Api.Infrastructure.Database.LotteryMode", "LotteryMode")
                        .WithMany()
                        .HasForeignKey("LotteryModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotteryMode");
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestNumber", b =>
                {
                    b.HasOne("LotoAnalytics.Api.Infrastructure.Database.Contest", "Contest")
                        .WithMany("Numbers")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestPrizeTier", b =>
                {
                    b.HasOne("LotoAnalytics.Api.Infrastructure.Database.Contest", "Contest")
                        .WithMany("PrizeTiers")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.ContestWinnerCity", b =>
                {
                    b.HasOne("LotoAnalytics.Api.Infrastructure.Database.Contest", "Contest")
                        .WithMany("WinnerCities")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("LotoAnalytics.Api.Infrastructure.Database.Contest", b =>
                {
                    b.Navigation("Numbers");

                    b.Navigation("PrizeTiers");

                    b.Navigation("WinnerCities");
                });
#pragma warning restore 612, 618
        }
    }
}
